
name: Check Format

on:
  push:
    paths:
      - "**.py"

jobs:
  formatting:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: black
      run: |
        python -m pip install --upgrade pip
        pip install black==22.1.0
        black --check .
    - name: flake8
      if: always()
      run: |
        pip install flake8==4.0.1
        flake8 .
    - name: isort
      if: always()
      run: |
        pip install isort==5.10.1
        isort . --check-only --recursive